let
    Source = #table(type table[Date Last Refreshed=datetime], {{DateTime.LocalNow()}}),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date Last Refreshed", type datetimezone}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Date Last Refreshed", "Last Refresh"}})
in
    #"Renamed Columns"

// This is a query that shows when the data was last refreshed.
